@echo off
REM ****************************************************************************
REM Vivado (TM) v2018.2 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Aug 18 04:08:09 +0530 2022
REM SW Build 2258646 on Thu Jun 14 20:03:12 MDT 2018
REM
REM Copyright 1986-2018 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim EnclosureNanoProcessor_TB_behav -key {Behavioral:sim_1:Functional:EnclosureNanoProcessor_TB} -tclbatch EnclosureNanoProcessor_TB.tcl -view E:/Sasindu/Vivado_Projects/UOM_CS1050/Lab9Enhanced3/NanoprocessorV3.xpr/Nanoprocessor/Nanoprocessor.srcs/sim_1/imports/Nanoprocessor/NanoProcessor_TB_behav3.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
